In [18]:
import numpy as np
a=np.array([1,2,3,4,5])
print("Array created",a)

Array created [1 2 3 4 5]


In [19]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Array created",a)

Array created [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [20]:
import numpy as np
a=np.zeros((3,5))
print("\n Array with zeros: \n",a)


 Array with zeros: 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [21]:
import numpy as np
s=np.random.random([2,3])
print("\n array with random values \n",s)


 array with random values 
 [[0.24494589 0.68943763 0.65297137]
 [0.78825523 0.52887444 0.25750109]]


In [22]:
import numpy as np
c=np.arange(0,55,5)
print("\nA sequence array with steps 5\n",c)



A sequence array with steps 5
 [ 0  5 10 15 20 25 30 35 40 45 50]


In [23]:
import numpy as op
f=np.array([[1,2,3],[4,5,6],[7,8,9]])
fl=f.flatten()
print("\n Original array:\n",f)
print("\n Flattend array:\n",fl)


 Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 Flattend array:
 [1 2 3 4 5 6 7 8 9]


In [24]:
print(a.ndim)

2


In [25]:
print(a.shape)

(3, 5)


In [26]:
print(a.dtype)

float64


In [27]:
print(a.size)

15


In [28]:
newtype=a.astype('f')
print("\n convert array:\n",newtype)
print("\n convert array:\n",newtype.dtype)


 convert array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

 convert array:
 float32


In [31]:
size=len(a)
print("\n size of array:\n",size)


 size of array:
 3
