In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
slice1=arr[2:6]
print(slice1)

[3 4 5 6]


In [ ]:
slice2=arr[::2]
print(slice2)

[1 3 5 7 9]


In [ ]:
rev_arr=arr[::-1]
print(rev_arr)

[9 8 7 6 5 4 3 2 1]


In [1]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
subarray=arr[0:3:2]
print(subarray)

[[1 2 3]
 [7 8 9]]


In [2]:
print(arr[0::2])

[[1 2 3]
 [7 8 9]]


In [3]:
print(arr[1::])

[[4 5 6]
 [7 8 9]]


In [4]:
print(arr[0,1:3])

[2 3]


In [5]:
print(arr[2:,2:])

[[9]]


In [ ]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[0])
print(arr[4])
print(arr[-1])
print(arr[1:4])
print(arr[arr>25])
print(arr[[1,3]])

10
50
50
[20 30 40]
[30 40 50]
[20 40]


In [7]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0,0])
print(arr[1,2])

1
6


In [ ]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.hstack((arr1,arr2))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
result1=np.hstack((arr1,arr2))
print(result1)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
result2=np.dstack((arr1,arr2))
print(result2)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [8]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
result=np.split(arr,3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [9]:
arr1=np.array([1,2,3,4,5])
result1=np.array_split(arr,3)
print(result1)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [25]:
arr2=np.array([[[1,2,3],[4,5,6]]])
result2=np.split(arr,2)
print(result2)

[array([1, 2, 3]), array([4, 5, 6])]


In [23]:
arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
result3=np.split(arr3,2)
print(result3)

[array([[[1, 2],
        [3, 4]]]), array([[[5, 6],
        [7, 8]]])]
